.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH eqr 1  "eqr 1.9.84" 
.SH NAME
eqr \- Encode text into svg/png/jpg/terminal\-format QR codes with optional logo
.SH SYNOPSIS
\fBqr\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-F\fR|\fB\-\-force\fR] [\fB\-t\fR|\fB\-\-terminal\fR] [\fB\-l\fR|\fB\-\-level\fR] [\fB\-p\fR|\fB\-\-path\fR] [\fB\-P\fR|\fB\-\-proportion\fR] [\fB\-e\fR|\fB\-\-edge\fR] [\fB\-f\fR|\fB\-\-fg\fR] [\fB\-b\fR|\fB\-\-bg\fR] [\fB\-s\fR|\fB\-\-scale\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fISTRING\fR] 
.SH DESCRIPTION
Encode text into svg/png/jpg/terminal\-format QR codes with optional logo
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<QR_PATH>\fR
Output file (jpg/png/svg) [default: qr.png]
.TP
\fB\-F\fR, \fB\-\-force\fR
Force the overwrite of an existing output file
.TP
\fB\-t\fR, \fB\-\-terminal\fR
Output to terminal (never the logo)
.TP
\fB\-l\fR, \fB\-\-level\fR \fI<LEVEL>\fR [default: M]
QR error correction level (L: 7%, M: 15%, Q: 25%, H: 30%)
.TP
\fB\-p\fR, \fB\-\-path\fR \fI<LOGO_PATH>\fR
Path to logo (png/jpg)
.TP
\fB\-P\fR, \fB\-\-proportion\fR \fI<PROPORTION>\fR [default: 0.25]
Logo proportion to the whole image (0..1)
.TP
\fB\-e\fR, \fB\-\-edge\fR \fI<EDGE>\fR [default: 4]
Edge size (in unit blocks)
.TP
\fB\-f\fR, \fB\-\-fg\fR \fI<FG>\fR [default: 000]
Foreground RGB color (hex code)
.TP
\fB\-b\fR, \fB\-\-bg\fR \fI<BG>\fR [default: fff]
Background RGB color (hex code)
.TP
\fB\-s\fR, \fB\-\-scale\fR \fI<SCALE>\fR [default: 8]
Size of unit block in pixels (1..255)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fISTRING\fR]
String to encode (can also be piped in)
.SH VERSION
v1.9.84
